"""users

Revision ID: 3b9e4d301d47
Revises: ffdc0a98111c
Create Date: 2021-11-16 12:54:36.463329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9e4d301d47'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImage', sa.String('http://clipart-library.com/new_gallery/280-2806732_png-file-svg-default-profile-picture-png.png')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###
